devtools::install_github("AndresMadrigalC/helllo-world/R CONNECTION.R")

#CONEXIÓN Y EXTRACCIÓN DE LA INFORMACIÓN DE LA BASE DE DATOS---------------
library(DBI)
#CREACIÓN DE LA CONEXIÓN A BASE DE DATOS
con <- dbConnect(odbc::odbc(),"PAYC_FACTURACION", uid="sa", pwd="1234JAMS*")
#EXTRACCIÓN DE LA INFORMACIÓN IMPORTANTE
INGRESOS_PERSONAS<-dbGetQuery(con, "SELECT * FROM FLUJO_INGRESOS_ROL")
INGRESOS_ITEMS<-dbGetQuery(con, "SELECT * FROM FLUJO_INGRESOS_ITEMS")

#CÁLCULO DE LOS VALORES TOTALES HISTÓRICOS A FACTURAR POR PERSONA E ÍTEM------------
TOTAL_PERSONAS<-aggregate(VALOR_CON_PRESTACIONES~ COD_FORMAS_PAGO_FECHAS+
                            COD_CONTRATO_PROYECTO+COD_ROL, data=INGRESOS_PERSONAS, sum)
TOTAL_ITEMS<-aggregate(VALOR_TOTAL~ COD_FORMAS_PAGO_FECHAS+COD_CONTRATO_PROYECTO
                       +COD_ITEM, data=INGRESOS_ITEMS, sum)

#CÁLCULO DEL VALOR TOTAL A FACTURAR POR CADA PROYECTO/MES
library(data.table)
FACTURADO<-rbindlist(list(TOTAL_ITEMS, TOTAL_PERSONAS))[, lapply(.SD, sum, na.rm = TRUE), 
                    by = c("COD_FORMAS_PAGO_FECHAS", "COD_CONTRATO_PROYECTO")]


#CÁLUCLO GENERAL DE VALOR A FACTURAR ----------------


