
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ASIGNACION_CARTERA
{

    public long COD_ASIGN_CARTERA { get; set; }

    public long COD_CARTERA { get; set; }

    public string UserName { get; set; }

    public System.DateTime FECHA_ASIGNACION { get; set; }



    public virtual CARTERA CARTERA { get; set; }

}

}
