
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CARTERA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CARTERA()
    {

        this.ACUERDOS_PAGO_ENTREGAB = new HashSet<ACUERDOS_PAGO_ENTREGAB>();

        this.ASIGNACION_CARTERA = new HashSet<ASIGNACION_CARTERA>();

        this.GESTION_CARTERA = new HashSet<GESTION_CARTERA>();

    }


    public long COD_CARTERA { get; set; }

    public Nullable<long> COD_FACTURA { get; set; }

    public Nullable<long> ESTADO_CARTERA { get; set; }

    public string UserName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<ACUERDOS_PAGO_ENTREGAB> ACUERDOS_PAGO_ENTREGAB { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<ASIGNACION_CARTERA> ASIGNACION_CARTERA { get; set; }

    public virtual ESTADOS_CARTERA ESTADOS_CARTERA { get; set; }

    public virtual FACTURAS FACTURAS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<GESTION_CARTERA> GESTION_CARTERA { get; set; }

}

}
