
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CARTERA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CARTERA()
    {

        this.COMPROMISOS_ENTREGABLES = new HashSet<COMPROMISOS_ENTREGABLES>();

        this.COMPROMISOS_PAGOS = new HashSet<COMPROMISOS_PAGOS>();

        this.GESTION_CARTERA = new HashSet<GESTION_CARTERA>();

    }


    public long COD_CARTERA { get; set; }

    public Nullable<long> COD_FACTURA { get; set; }

    public string ESTADO_CARTERA { get; set; }

    public Nullable<long> COD_RECIBO_PAGO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<COMPROMISOS_ENTREGABLES> COMPROMISOS_ENTREGABLES { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<COMPROMISOS_PAGOS> COMPROMISOS_PAGOS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<GESTION_CARTERA> GESTION_CARTERA { get; set; }

}

}
