
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CENTROS_COSTOS
{

    public long COD_CECO { get; set; }

    public string CECO_PSL { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<long> COD_ESTADO_CECO { get; set; }



    public virtual ESTADOS_CECO ESTADOS_CECO { get; set; }

}

}
