//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTROS_COSTOS
    {
        public long COD_CECO { get; set; }
        public string CECO_PSL { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<long> COD_ESTADO_CECO { get; set; }
    
        public virtual ESTADOS_CECO ESTADOS_CECO { get; set; }
    }
}
