
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CHECK_COLABORADOR_MES
{

    public Nullable<long> COD_ROL { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<System.DateTime> FECHA_FORMA_PAGO { get; set; }

    public Nullable<int> CUENTA { get; set; }

    public string ROL_TEXTO { get; set; }

}

}
