
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class COLABORADORES_CONTAR_ESTUDIOS
{

    public long COD_COLABORADOR { get; set; }

    public Nullable<long> COD_CARGO { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<long> CEDULA { get; set; }

    public string GENERO { get; set; }

    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }

    public string CELULAR { get; set; }

    public string CORREO_ELECTRONICO { get; set; }

    public string ESTADO_CIVIL { get; set; }

    public string CENTROS_COSTOS { get; set; }

    public Nullable<System.DateTime> FECHA_INGRESO { get; set; }

    public string TIPO_DE_CONTRATO { get; set; }

    public string ESTADO { get; set; }

    public string Estudios { get; set; }

}

}
