
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class COMBINACIONES_GASTOS_ADMINISTRATIVOS
{

    public long ID { get; set; }

    public string CALCULO { get; set; }

    public Nullable<int> CUENTA { get; set; }

    public Nullable<long> SIGNO { get; set; }

}

}
