//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATOS()
        {
            this.CONTRATO_PROYECTO = new HashSet<CONTRATO_PROYECTO>();
        }
    
        public long COD_CONTRATO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<long> COD_CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_FIRMA { get; set; }
        public string RUTA_ACTA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_EJECUCION { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_EJECUCION { get; set; }
        public Nullable<float> VALOR_CONTRATO { get; set; }
        public string ORDEN_SERVICIO { get; set; }
        public string RUTA_DOCUMENTO { get; set; }
    
        internal virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[System.Runtime.Serialization.IgnoreDataMember]
    	[Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<CONTRATO_PROYECTO> CONTRATO_PROYECTO { get; set; }
    }
}
