
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRATOS_CONDICIONES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CONTRATOS_CONDICIONES()
    {

        this.ENTREGABLES = new HashSet<ENTREGABLES>();

    }


    public long COD_CONTRATO_CONDICION { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_TIPO_CONDICION { get; set; }

    public string VIGENTE { get; set; }

    public Nullable<System.DateTime> FECHA_INCLUSION { get; set; }

    public Nullable<System.DateTime> FECHA_EXCLUSION { get; set; }



    public virtual CONTRATO_PROYECTO CONTRATO_PROYECTO { get; set; }

    public virtual TIPO_CONDICION_CONTRACTUAL TIPO_CONDICION_CONTRACTUAL { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<ENTREGABLES> ENTREGABLES { get; set; }

}

}
