
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRATO_COLABORADOR_INDEX
{

    public long COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_CONTRATO { get; set; }

    public string ORDEN_SERVICIO { get; set; }

    public string CENTRO_COSTOS { get; set; }

    public Nullable<System.DateTime> FECHA_INICIO_EJECUCION { get; set; }

    public Nullable<System.DateTime> FECHA_FIN_EJECUCION { get; set; }

    public string DESCRIPCION { get; set; }

    public string TIPO_OBRA { get; set; }

    public string TIPO_SERVICIO { get; set; }

}

}
