//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS_CONDICIONES_VISTA
    {
        public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }
        public Nullable<long> COD_CONTRATO { get; set; }
        public Nullable<long> COD_PROYECTO { get; set; }
        public Nullable<long> COD_FORMA_PAGO { get; set; }
        public string COMPLETA { get; set; }
        public string MODIFICADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_MODIFICACION { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string CENTRO_COSTOS { get; set; }
        public long COD_CONTRATO_CONDICION { get; set; }
        public Nullable<long> Expr1 { get; set; }
        public Nullable<long> COD_TIPO_CONDICION { get; set; }
        public string VIGENTE { get; set; }
        public Nullable<System.DateTime> FECHA_INCLUSION { get; set; }
        public Nullable<System.DateTime> FECHA_EXCLUSION { get; set; }
    }
}
