
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRATOS_PROYECCION
{

    public string CENTRO_COSTOS { get; set; }

    public long COD_CONTRATOS_PROYECCION { get; set; }

    public Nullable<System.DateTime> FECHA_INI { get; set; }

    public Nullable<System.DateTime> FECHA_FIN { get; set; }

    public string COMENTARIOS { get; set; }

    public string VA { get; set; }

    public Nullable<System.DateTime> FECHA_FIN_CORREGIDA { get; set; }

    public Nullable<System.DateTime> FECHA_ESCRITA { get; set; }

    public string TIENE_MODIFICACIONES_FLUJO { get; set; }

    public Nullable<System.DateTime> FECHA_FIN_FIN { get; set; }

}

}
