//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test_payc_contabilidadEntities : DbContext
    {
        public test_payc_contabilidadEntities()
            : base("name=test_payc_contabilidadEntities")
        {
    	this.Configuration.ProxyCreationEnabled = false; 
    	this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGOS> CARGOS { get; set; }
        public virtual DbSet<CARTERA> CARTERA { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMPROMISOS_ENTREGABLES> COMPROMISOS_ENTREGABLES { get; set; }
        public virtual DbSet<COMPROMISOS_PAGOS> COMPROMISOS_PAGOS { get; set; }
        public virtual DbSet<CONTRATO_COLABORADOR> CONTRATO_COLABORADOR { get; set; }
        public virtual DbSet<CONTRATOS> CONTRATOS { get; set; }
        public virtual DbSet<CONTRATOS_CONDICIONES> CONTRATOS_CONDICIONES { get; set; }
        public virtual DbSet<DETALLE_FACTURA_ITEM> DETALLE_FACTURA_ITEM { get; set; }
        public virtual DbSet<ENTREGABLES> ENTREGABLES { get; set; }
        public virtual DbSet<ESTUDIOS_COLABORADOR> ESTUDIOS_COLABORADOR { get; set; }
        public virtual DbSet<FACTURAS> FACTURAS { get; set; }
        public virtual DbSet<FLUJO_INGRESOS_ITEMS> FLUJO_INGRESOS_ITEMS { get; set; }
        public virtual DbSet<FLUJO_INGRESOS_ROL> FLUJO_INGRESOS_ROL { get; set; }
        public virtual DbSet<FORMAS_PAGO_FECHAS> FORMAS_PAGO_FECHAS { get; set; }
        public virtual DbSet<GESTION_CARTERA> GESTION_CARTERA { get; set; }
        public virtual DbSet<ITEMS_CONTRATO> ITEMS_CONTRATO { get; set; }
        public virtual DbSet<REGISTRO_ITEMS_OTROS_COSTOS> REGISTRO_ITEMS_OTROS_COSTOS { get; set; }
        public virtual DbSet<REGISTRO_NOVEDADES> REGISTRO_NOVEDADES { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<TIPO_CONDICION_CONTRACTUAL> TIPO_CONDICION_CONTRACTUAL { get; set; }
        public virtual DbSet<TIPOS_NOVEDAD> TIPOS_NOVEDAD { get; set; }
        public virtual DbSet<TIPOS_NOVEDAD_CONDICION> TIPOS_NOVEDAD_CONDICION { get; set; }
        public virtual DbSet<CONTRATO_PROYECTO_DESCRIPCION> CONTRATO_PROYECTO_DESCRIPCION { get; set; }
        public virtual DbSet<VISTA_FLUJO_INGRESOS> VISTA_FLUJO_INGRESOS { get; set; }
        public virtual DbSet<VISTA_FLUJO_INGRESOS_ITEMS> VISTA_FLUJO_INGRESOS_ITEMS { get; set; }
        public virtual DbSet<GENERACION_FLUJOS_ROL> GENERACION_FLUJOS_ROL { get; set; }
        public virtual DbSet<SINO> SINO { get; set; }
        public virtual DbSet<GENERACION_FLUJOS_ITEM> GENERACION_FLUJOS_ITEM { get; set; }
        public virtual DbSet<GENERACION_FLUJOS_ITEM3> GENERACION_FLUJOS_ITEM3 { get; set; }
        public virtual DbSet<GENERACION_FLUJOS_ROL3> GENERACION_FLUJOS_ROL3 { get; set; }
        public virtual DbSet<PENDIENTES> PENDIENTES { get; set; }
        public virtual DbSet<CONTRATO_COLABORADOR_INDEX> CONTRATO_COLABORADOR_INDEX { get; set; }
        public virtual DbSet<GENEROS> GENEROS { get; set; }
        public virtual DbSet<TIPO_CONTRATO> TIPO_CONTRATO { get; set; }
        public virtual DbSet<COLARADORES_CONCAT_ESTUDIOS> COLARADORES_CONCAT_ESTUDIOS { get; set; }
        public virtual DbSet<ESTADO_COLABORADOR> ESTADO_COLABORADOR { get; set; }
        public virtual DbSet<CONTRATOS_CONDICIONES_VISTA> CONTRATOS_CONDICIONES_VISTA { get; set; }
        public virtual DbSet<TIPOS_TRIBUTACION> TIPOS_TRIBUTACION { get; set; }
        public virtual DbSet<CONTRATO_PROYECTO> CONTRATO_PROYECTO { get; set; }
        public virtual DbSet<FORMAS_PAGO> FORMAS_PAGO { get; set; }
        public virtual DbSet<CONTRATOS_ROL> CONTRATOS_ROL { get; set; }
        public virtual DbSet<PROYECTOS> PROYECTOS { get; set; }
        public virtual DbSet<TIPOS_OBRA> TIPOS_OBRA { get; set; }
        public virtual DbSet<TIPOS_SERVICIOS> TIPOS_SERVICIOS { get; set; }
        public virtual DbSet<INCREMENTO_SALARIAL> INCREMENTO_SALARIAL { get; set; }
        public virtual DbSet<TAG_ORDEN> TAG_ORDEN { get; set; }
        public virtual DbSet<COLABORADORES> COLABORADORES { get; set; }
        public virtual DbSet<INCREMENTO_ORDEN> INCREMENTO_ORDEN { get; set; }
        public virtual DbSet<TIPOS_REEMBOLSO> TIPOS_REEMBOLSO { get; set; }
        public virtual DbSet<ORDENES_SERVICIO_INDEX> ORDENES_SERVICIO_INDEX { get; set; }
        public virtual DbSet<CONTRATO_ROL_CARGO> CONTRATO_ROL_CARGO { get; set; }
        public virtual DbSet<VISTA_ORDENES_ROL_CARGO> VISTA_ORDENES_ROL_CARGO { get; set; }
        public virtual DbSet<DETALLE_FACTURA_PERS> DETALLE_FACTURA_PERS { get; set; }
        public virtual DbSet<CONTRATO_COLABORADOR_COMERCIAL> CONTRATO_COLABORADOR_COMERCIAL { get; set; }
        public virtual DbSet<VISTA_PENDIENTES_RETIRO> VISTA_PENDIENTES_RETIRO { get; set; }
        public virtual DbSet<VISTA_PENDIENTES_FACTURA> VISTA_PENDIENTES_FACTURA { get; set; }
    }
}
