
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRATO_COLABORADOR_COMERCIAL
{

    public long COD_CONTRATO_COLABORADOR { get; set; }

    public Nullable<long> COD_COLABORADOR { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_ROL { get; set; }

    public Nullable<System.DateTime> FECHA_INI_COLABORADOR { get; set; }

    public Nullable<System.DateTime> FECHA_FIN { get; set; }

    public string FECHA_INI_COMERCIAL { get; set; }

    public Nullable<long> MESES { get; set; }

    public Nullable<decimal> VALOR_MENSUAL_SIN_PRESTACIONES { get; set; }

    public Nullable<decimal> VALOR_MENSUAL_PRESTACIONES { get; set; }

    public Nullable<decimal> VALOR_MENSUAL_PRESTACIONES_MULTIPLICADOR { get; set; }

    public Nullable<decimal> DEDICACION { get; set; }

    public string OBSERVACIONES { get; set; }

    public string TIPO_SERVICIO { get; set; }

    public string TIPO_OBRA { get; set; }

    public string RUTA_DOCUMENTO { get; set; }

    public Nullable<long> COD_CONTRATO_ROL { get; set; }

    public string DESCRIPCION_CARGO { get; set; }

}

}
