
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DETALLE_FACTURA_ITEMPERS
{

    public Nullable<long> COD_FACTURA { get; set; }

    public long CAD_DETALLE_FACTURA { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_ITEMPERS_CONTRATO { get; set; }

    public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }

    public Nullable<decimal> VALOR_SIN_IMPUESTOS { get; set; }

    public Nullable<long> COD_CAUSA_ESTADO { get; set; }

    public Nullable<long> COD_ESTADO_DETALLE { get; set; }

    public Nullable<long> COD_GRUPO_FACTURA { get; set; }

    public Nullable<long> COD_CONCEPTO_PSL { get; set; }

    public Nullable<System.DateTime> PERIODO_FACTURA { get; set; }

}

}
