//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIOS_COLABORADOR_TEMP
    {
        public long COD_ESTUDIOS { get; set; }
        public string COD_COLABORADOR { get; set; }
        public string NIVEL_ESTUDIO { get; set; }
        public string TITULO_ESTUDIO { get; set; }
        public Nullable<System.DateTime> FECHA_GRADO { get; set; }
        public string INSTITUCION_GRADO { get; set; }
    }
}
