//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTORES_REALES
    {
        public long COD_FACTOR_REAL { get; set; }
        public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }
        public Nullable<long> CECO { get; set; }
        public Nullable<decimal> ITEMS_NO_REEMB { get; set; }
        public Nullable<decimal> PERSONAL_NO_REEMB { get; set; }
        public Nullable<decimal> REEMBOLSABLES { get; set; }
    }
}
