
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GENERACION_FLUJOS_ITEM
{

    public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }

    public long COD_ITEM_CONTRATO { get; set; }

    public Nullable<decimal> VALOR_VARIABLE_UNITARIO { get; set; }

    public Nullable<decimal> VALOR_VARIABLE { get; set; }

    public Nullable<decimal> VALOR_FIJO { get; set; }

    public Nullable<decimal> VALOR_FIJO_UNITARIO { get; set; }

    public Nullable<decimal> VALOR_TOTAL { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

}

}
