//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERACION_FLUJOS_ITEM2
    {
        public long COD_ITEM_CONTRATO { get; set; }
        public int VALOR_VARIABLE_UNITARIO { get; set; }
        public int VALOR_VARIABLE { get; set; }
        public int VALOR_TOTAL { get; set; }
        public int VALOR_FIJO_UNITARIO { get; set; }
        public int VALOR_FIJO { get; set; }
        public long COD_FORMAS_PAGO_FECHAS { get; set; }
        public long COD_CONTRATO_PROYECTO { get; set; }
        public string ETAPA { get; set; }
    }
}
