
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GESTION_CARTERA
{

    public long COD_GESTION { get; set; }

    public Nullable<long> COD_CARTERA { get; set; }

    public string UserName { get; set; }

    public Nullable<long> TIPO_GESTION { get; set; }

    public Nullable<System.DateTime> FECHA_GESTION { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }



    public virtual CARTERA CARTERA { get; set; }

    public virtual CONTRATO_PROYECTO CONTRATO_PROYECTO { get; set; }

    public virtual TIPOS_GESTION TIPOS_GESTION { get; set; }

}

}
