
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ITEMS_CONTRATO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ITEMS_CONTRATO()
    {

        this.DETALLE_FACTURA_ITEM = new HashSet<DETALLE_FACTURA_ITEM>();

        this.FLUJO_INGRESOS_ITEMS = new HashSet<FLUJO_INGRESOS_ITEMS>();

        this.REGISTRO_ITEMS_OTROS_COSTOS = new HashSet<REGISTRO_ITEMS_OTROS_COSTOS>();

    }


    public long COD_ITEM_CONTRATO { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_ITEM { get; set; }

    public string ITEM_REEMBOLZABLE { get; set; }

    public string REUTILIZABLE { get; set; }

    public Nullable<float> COSTO_INICIAL_UNITARIO { get; set; }

    public Nullable<float> COSTO_MENSUAL_UNITARIO { get; set; }

    public Nullable<long> CANTIDAD { get; set; }

    public Nullable<System.DateTime> FECHA_INI_USO { get; set; }

    public Nullable<long> MESES_USO { get; set; }

    public string OBSERVACIONES { get; set; }

    public Nullable<long> COD_TIPO_REEMBOLSO { get; set; }

    public Nullable<long> DIAS_FRACCION { get; set; }

    public Nullable<long> COD_CONCEPTO_PSL { get; set; }



    public virtual CONCEPTOS CONCEPTOS { get; set; }

    public virtual CONTRATO_PROYECTO CONTRATO_PROYECTO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<DETALLE_FACTURA_ITEM> DETALLE_FACTURA_ITEM { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<FLUJO_INGRESOS_ITEMS> FLUJO_INGRESOS_ITEMS { get; set; }

    public virtual ITEMS ITEMS { get; set; }

    public virtual TIPOS_REEMBOLSO TIPOS_REEMBOLSO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<REGISTRO_ITEMS_OTROS_COSTOS> REGISTRO_ITEMS_OTROS_COSTOS { get; set; }

}

}
