
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ITEMS_ROLES
{

    public long COD_ITEM_ROL { get; set; }

    public Nullable<long> COD_ITEM_CONTRATO { get; set; }

    public Nullable<long> COD_ROL { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }



    public virtual ITEMS_CONTRATO ITEMS_CONTRATO { get; set; }

    public virtual ROLES ROLES { get; set; }

    public virtual CONTRATO_PROYECTO CONTRATO_PROYECTO { get; set; }

}

}
