
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ITEMS_CONTRATO_DESCRIPCION
{

    public long COD_ITEM_CONTRATO { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_ITEM { get; set; }

    public string ITEM_REEMBOLZABLE { get; set; }

    public string REUTILIZABLE { get; set; }

    public Nullable<float> COSTO_INICIAL_UNITARIO { get; set; }

    public Nullable<float> COSTO_MENSUAL_UNITARIO { get; set; }

    public Nullable<long> CANTIDAD { get; set; }

    public Nullable<System.DateTime> FECHA_INI_USO { get; set; }

    public Nullable<long> MESES_USO { get; set; }

    public string OBSERVACIONES { get; set; }

    public Nullable<long> COD_TIPO_REEMBOLSO { get; set; }

    public Nullable<long> DIAS_FRACCION { get; set; }

    public string DESCRIPCION { get; set; }

}

}
