
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ORDENES_SERVICIO_ROLES_COLABORADOR
{

    public Nullable<long> COD_ROL { get; set; }

    public string ETAPA { get; set; }

    public Nullable<float> VALOR_SIN_PRESTACIONES { get; set; }

    public Nullable<float> VALOR_CON_PRESTACIONES { get; set; }

    public Nullable<float> VALOR_FACTOR_MULTIPLICADOR { get; set; }

    public string DESCRIPCION { get; set; }

    public string ORDEN_SERVICIO { get; set; }

    public string PROYECTO { get; set; }

    public string TIPO_SERVICIO { get; set; }

    public string TIPO_OBRA { get; set; }

    public long COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<System.DateTime> FECHA_FORMA_PAGO { get; set; }

    public Nullable<long> COD_COLABORADOR { get; set; }

    public string NOMBRE { get; set; }

    public string ROL_TEXTO { get; set; }

}

}
