
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PROYECTOS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PROYECTOS()
    {

        this.CONTRATO_PROYECTO = new HashSet<CONTRATO_PROYECTO>();

    }


    public long COD_PROYECTO { get; set; }

    public string CENTRO_COSTOS { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<float> AREA { get; set; }

    public Nullable<long> PLAZO_PREVIA { get; set; }

    public Nullable<System.DateTime> FECHA_INI_PREVIA { get; set; }

    public Nullable<long> PLAZO_OBRA { get; set; }

    public Nullable<System.DateTime> FECHA_INI_OBRA { get; set; }

    public Nullable<long> PLAZO_LIQUIDACION { get; set; }

    public Nullable<System.DateTime> FECHA_INI_LIQUIDACION { get; set; }

    public string ESTRUCTURA { get; set; }

    public string CIMENTACION { get; set; }

    public Nullable<long> SOTANOS { get; set; }

    public Nullable<long> PISOS { get; set; }

    public Nullable<float> VALOR_PROYECTO { get; set; }

    public string DIRECCION { get; set; }

    public Nullable<long> COD_TIPO_SERVICIO { get; set; }

    public Nullable<long> COD_TIPO_OBRA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
	[System.Runtime.Serialization.IgnoreDataMember]
	[Newtonsoft.Json.JsonIgnore]

    public virtual ICollection<CONTRATO_PROYECTO> CONTRATO_PROYECTO { get; set; }

    public virtual TIPOS_OBRA TIPOS_OBRA { get; set; }

    public virtual TIPOS_SERVICIOS TIPOS_SERVICIOS { get; set; }

}

}
