//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_NOVEDADES_TRABAJO
    {
        public long COD_REGISTRO_NOVEDADES { get; set; }
        public Nullable<long> COD_COLABORADOR { get; set; }
        public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }
        public Nullable<long> COD_TIPO_NOVEDAD { get; set; }
        public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_NOVEDAD { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_NOVEDAD { get; set; }
    
        public virtual COLABORADORES COLABORADORES { get; set; }
        public virtual CONTRATO_PROYECTO CONTRATO_PROYECTO { get; set; }
        public virtual FORMAS_PAGO_FECHAS FORMAS_PAGO_FECHAS { get; set; }
        public virtual TIPOS_NOVEDAD TIPOS_NOVEDAD { get; set; }
    }
}
