//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMULACION_PAGOS
    {
        public long COD_SIMULACION { get; set; }
        public Nullable<System.DateTime> FECHA_SIMULACION { get; set; }
        public string VARIABLE { get; set; }
        public string CECO { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public Nullable<long> DIAS_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<decimal> VALOR_PAGADO { get; set; }
        public string ORIGEN { get; set; }
    }
}
