
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TIPOS_NOVEDAD_CONDICION
{

    public long COD_TIPO_NOVEDAD_CONDICION { get; set; }

    public Nullable<long> COD_TIPO_NOVEDAD { get; set; }

    public Nullable<long> COD_TIPO_CONDICION { get; set; }



    public virtual TIPO_CONDICION_CONTRACTUAL TIPO_CONDICION_CONTRACTUAL { get; set; }

    public virtual TIPOS_NOVEDAD TIPOS_NOVEDAD { get; set; }

}

}
