//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAZA_FACTURA_PSL_PRUEBAS
    {
        public long COD_TRAZA_PSL { get; set; }
        public Nullable<long> COD_FACTURA { get; set; }
        public string NUM_FACT_PSL_PRUEBAS { get; set; }
        public Nullable<decimal> TOTAL_FACTURA { get; set; }
    
        public virtual FACTURAS FACTURAS { get; set; }
    }
}
