
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_CARTERA_INDEX
{

    public long COD_CLIENTE { get; set; }

    public string DESCRIPCION { get; set; }

    public string GESTOR { get; set; }

    public Nullable<decimal> VALOR_SIN_IMPUESTOS { get; set; }

    public string NUMERO_FACTURA { get; set; }

    public Nullable<System.DateTime> FECHA_FACTURA { get; set; }

    public Nullable<long> ESTADO_CARTERA { get; set; }

    public string RANKING { get; set; }

    public long COD_FACTURA { get; set; }

    public long COD_CARTERA { get; set; }

}

}
