//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_DETALLE_FACTURAS_REPORTE
    {
        public long ID { get; set; }
        public string NOMBRE_PROYECTO { get; set; }
        public string NOMBRE_ROL { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_RETIRO_EN_CONTRATO { get; set; }
        public Nullable<decimal> VALOR_SIN_IMPUESTOS { get; set; }
        public Nullable<decimal> VALOR_DIAS_LAB { get; set; }
        public Nullable<decimal> ADICIONES { get; set; }
        public Nullable<decimal> DESCUENTO_AUSENCIA { get; set; }
        public Nullable<decimal> HORAS_ED { get; set; }
        public Nullable<decimal> HORAS_EN { get; set; }
        public Nullable<decimal> HORAS_FD { get; set; }
        public Nullable<decimal> HORAS_FN { get; set; }
        public Nullable<decimal> HORAS_AUSENCIA { get; set; }
        public string NOVEDADES { get; set; }
        public string CENTRO_COSTOS { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public Nullable<System.DateTime> PERIODO_FACTURACION { get; set; }
        public Nullable<long> COD_ROL { get; set; }
        public Nullable<decimal> SALARIO_COMERCIAL_SIN_PRESTACIONES_CON_INCREMENTOS { get; set; }
        public Nullable<decimal> PRESTACIONES { get; set; }
        public long COD_CONTRATO_PROYECTO { get; set; }
        public string TIPO_ELEMENTO { get; set; }
        public Nullable<decimal> HORAS_EXTRA { get; set; }
        public Nullable<decimal> DIAS_AUSENCIA { get; set; }
    }
}
