//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_COSTOS_FLUJO_INGR
    {
        public Nullable<long> FILA { get; set; }
        public long COD_CONTRATO_PROYECTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<float> VALOR_TOTAL { get; set; }
    }
}
