
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_DETALLE_ADJUNTO_PERS_EXPORT
{

    public Nullable<long> ID { get; set; }

    public Nullable<long> COD_FACTURA { get; set; }

    public string NOMBRE_PROYECTO { get; set; }

    public string NOMBRE_ROL { get; set; }

    public string NOMBRE_PERSONA { get; set; }

    public Nullable<System.DateTime> FECHA_INGRESO { get; set; }

    public Nullable<System.DateTime> FECHA_RETIRO_EN_CONTRATO { get; set; }

    public Nullable<decimal> VALOR_SIN_IMPUESTOS { get; set; }

    public Nullable<decimal> VALOR_DIAS_LAB { get; set; }

    public Nullable<decimal> ADICIONES { get; set; }

    public Nullable<decimal> DESCUENTO_AUSENCIA { get; set; }

    public Nullable<decimal> HORAS_ED { get; set; }

    public Nullable<decimal> HORAS_EN { get; set; }

    public Nullable<decimal> HORAS_FD { get; set; }

    public Nullable<decimal> HORAS_FN { get; set; }

    public Nullable<decimal> HORAS_AUSENCIA { get; set; }

    public string NOVEDADES { get; set; }

}

}
