//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ORDENES_ROL_CARGO
    {
        public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }
        public long COD_CONTRATO_ROL { get; set; }
        public long COD_COLABORADOR { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<long> COD_CARGO { get; set; }
        public string DESCRIPCION_CARGO { get; set; }
    }
}
