//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ENCDOCVTAENTRA_MULTIPLES_FACTURAS_PRODUCTIVO
    {
        public long edvconseingre { get; set; }
        public string edvcontrol { get; set; }
        public Nullable<decimal> edvvaloconimp { get; set; }
        public string edvnumedocuclie { get; set; }
        public string edvtipoconsclie { get; set; }
        public string edvcompania { get; set; }
        public string edvtipodocuclie { get; set; }
        public string edvclasdocuclie { get; set; }
        public string edvdivision { get; set; }
        public string edvcliente { get; set; }
        public string edvconcepto { get; set; }
        public string edvmoneda { get; set; }
        public Nullable<decimal> edvtotamoneloca { get; set; }
        public Nullable<decimal> edvtotamonenego { get; set; }
        public string edvcentroresp { get; set; }
        public string eobusuario { get; set; }
        public Nullable<System.DateTime> edvfechexpe { get; set; }
        public Nullable<System.DateTime> edvfechaconta { get; set; }
        public Nullable<decimal> edvvalobruto { get; set; }
        public Nullable<decimal> edvvaloneto { get; set; }
        public Nullable<System.DateTime> edvfechinteobra { get; set; }
        public string edvformapago { get; set; }
        public string edvidentificador { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }
        public string edvcomentario { get; set; }
    }
}
