//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_FACTURAS_PAGOS
    {
        public string COMPAÑIA { get; set; }
        public string CECO { get; set; }
        public string FACTURA { get; set; }
        public Nullable<decimal> FALTANTE { get; set; }
        public Nullable<decimal> edvvaloneto { get; set; }
        public Nullable<decimal> TOTAL_PAGO { get; set; }
    }
}
