//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ORDENES_CENTRO_COSTOS
    {
        public long COD_CONTRATO_PROYECTO { get; set; }
        public Nullable<long> COD_CONTRATO { get; set; }
        public Nullable<long> COD_PROYECTO { get; set; }
        public Nullable<long> COD_FORMA_PAGO { get; set; }
        public string COMPLETA { get; set; }
        public string MODIFICADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_MODIFICACION { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string CENTRO_COSTOS { get; set; }
        public Nullable<long> COD_ESTADO_ORDEN_SERVICIO { get; set; }
        public string ESTADO_PSL { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_EJECUCION { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_EJECUCION { get; set; }
        public string ESTADO_CENTRO_COSTO { get; set; }
    }
}
