//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_DETALLE_FACTURA_ITEM_REPORTE_PSL
    {
        public string NOMBRE_PROYECTO { get; set; }
        public string NOMBRE_ROL { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public string FECHA_INGRESO { get; set; }
        public string FECHA_RETIRO_EN_CONTRATO { get; set; }
        public Nullable<decimal> VALOR_SIN_IMPUESTOS { get; set; }
        public int VALOR_DIAS_LAB { get; set; }
        public int ADICIONES { get; set; }
        public int DESCUENTO_AUSENCIA { get; set; }
        public int HORAS_ED { get; set; }
        public int HORAS_EN { get; set; }
        public int HORAS_FD { get; set; }
        public int HORAS_FN { get; set; }
        public int HORAS_AUSENCIA { get; set; }
        public string NOVEDADES { get; set; }
        public string CENTRO_COSTOS { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public string NUMERO_FACTURA_PRODUCTIVO { get; set; }
        public Nullable<System.DateTime> PERIODO_FACTURACION { get; set; }
        public int COD_ROL { get; set; }
        public int SALARIO_COMERCIAL_SIN_PRESTACIONES { get; set; }
        public int PRESTACIONES { get; set; }
        public long COD_CONTRATO_PROYECTO { get; set; }
        public string DEDICACION { get; set; }
        public Nullable<long> COD_FACTURA { get; set; }
    }
}
