
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_CARTERA_INDEX1
{

    public Nullable<long> ID { get; set; }

    public long COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_CLIENTE { get; set; }

    public string DESCRIPCION { get; set; }

    public string GESTOR { get; set; }

    public Nullable<decimal> SALDO { get; set; }

    public Nullable<System.DateTime> FECHA_FACTURA { get; set; }

    public string RANKING { get; set; }

    public string CENTRO_COSTOS { get; set; }

    public Nullable<decimal> RANK1 { get; set; }

}

}
