
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_COSTOS_FLUJO_INGR
{

    public Nullable<long> FILA { get; set; }

    public long COD_CONTRATO_PROYECTO { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<System.DateTime> FECHA { get; set; }

    public Nullable<float> VALOR_TOTAL { get; set; }

    public string CENTRO_COSTOS { get; set; }

}

}
