//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_TOTALES_GRUPOS_FACTURAS_SECUENCIA_PRODUCTIVO
    {
        public Nullable<long> COD_FACTURA { get; set; }
        public Nullable<long> COD_GRUPO_FACTURA { get; set; }
        public decimal TOTAL_FACTURA { get; set; }
        public Nullable<long> SECUENCIA_NUM_FACT_PSL { get; set; }
    }
}
