
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_SALARIO_COMERCIAL_INCREMENTOS
{

    public long COD_FORMAS_PAGO_FECHAS { get; set; }

    public Nullable<long> COD_ROL { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public string Expr1 { get; set; }

    public Nullable<decimal> VALOR_MENSUAL_SIN_PRESTACIONES { get; set; }

    public Nullable<decimal> VALOR_MENSUAL_PRESTACIONES { get; set; }

    public Nullable<decimal> VALOR_MENSUAL_PRESTACIONES_MULTIPLICADOR { get; set; }

    public Nullable<decimal> SALARIO_COMERCIAL { get; set; }

}

}
