//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_FACTURAS_FECHA_PERIODO_FACTURACION
    {
        public long COD_FACTURA { get; set; }
        public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }
        public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public Nullable<long> COD_ESTADO_FACTURA { get; set; }
        public Nullable<decimal> VALOR_SIN_IMPUESTOS { get; set; }
        public Nullable<decimal> VALOR_CON_IMPUESTOS { get; set; }
        public string RANKING { get; set; }
        public Nullable<System.DateTime> FECHA_FORMA_PAGO { get; set; }
    }
}
