//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_DETDOCVTAENTRA_MULTIPLES_FACTURAS_PRODUCTIVO
    {
        public long ddvconseingre { get; set; }
        public string ddvcontrol { get; set; }
        public string ddvcompania { get; set; }
        public string ddvnumedocu { get; set; }
        public string ddvtipocons { get; set; }
        public Nullable<long> ddvconseregis { get; set; }
        public string ddvconcecxc { get; set; }
        public string ddvunidaventa { get; set; }
        public string ddvunidaempaq { get; set; }
        public int ddvcanfacunivta { get; set; }
        public int ddvcanfacuniemp { get; set; }
        public Nullable<decimal> ddvprecunitbrut { get; set; }
        public Nullable<decimal> ddvprecunitneto { get; set; }
        public Nullable<decimal> ddvprectotabrut { get; set; }
        public Nullable<decimal> ddvprectotaneto { get; set; }
        public string ddvdivision { get; set; }
        public string ddvcentrorespo { get; set; }
        public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public string ddvcomentario { get; set; }
    }
}
