//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_FACTURAS_FECHA_PERIODO_FACTURACION
    {
        public long COD_FACTURA { get; set; }
        public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }
        public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public Nullable<long> COD_ESTADO_FACTURA { get; set; }
        public Nullable<float> VALOR_SIN_IMPUESTOS { get; set; }
        public Nullable<float> VALOR_CON_IMPUESTOS { get; set; }
        public string RANKING { get; set; }
        public Nullable<System.DateTime> FECHA_FORMA_PAGO { get; set; }
    }
}
