
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_INDICADORES_PROYECCION_PAGOS
{

    public Nullable<System.DateTime> FECHA_PAGO { get; set; }

    public string CECO { get; set; }

    public Nullable<decimal> VALOR { get; set; }

    public string VARIABLE { get; set; }

}

}
