
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_RESUMEN_FACTURACION
{

    public string CENTRO_COSTOS { get; set; }

    public Nullable<long> COD_ESTADO_ORDEN_SERVICIO { get; set; }

    public string COMPLETA { get; set; }

    public string DESCRIPCION { get; set; }

    public long COD_CONTRATO_PROYECTO { get; set; }

    public System.DateTime FECHA_ULTIMA_FACTURA { get; set; }

    public Nullable<int> DIAS_SIN_FACTURAR { get; set; }

    public Nullable<int> MESES_SIN_FACTURAR { get; set; }

    public System.DateTime FECHA_INICIO_EJECUCION_ULTIMO_CONTRATO { get; set; }

    public string ESTADO_ULTIMA_FACTURA { get; set; }

    public string ESTADO_ORDEN { get; set; }

    public Nullable<decimal> TOTAL_SIN_IMPUESTOS { get; set; }

    public Nullable<double> TOTAL_CONTRATOS { get; set; }

    public Nullable<decimal> TOTAL_CON_IMPUESTOS { get; set; }

    public Nullable<decimal> TOTAL_SALDO { get; set; }

}

}
