
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_FINANCIERA
{

    public decimal AÑO { get; set; }

    public decimal PERIODO { get; set; }

    public string FUENTE { get; set; }

    public decimal COMPROBANTE { get; set; }

    public string CUENTA { get; set; }

    public Nullable<int> Nivel1 { get; set; }

    public Nullable<int> Nivel2 { get; set; }

    public Nullable<int> Nivel4 { get; set; }

    public Nullable<int> Nivel6 { get; set; }

    public Nullable<decimal> DEBITO { get; set; }

    public Nullable<decimal> CREDITO { get; set; }

    public Nullable<decimal> NETO { get; set; }

    public string CECO { get; set; }

    public string CECO_NOMBRE { get; set; }

    public string TERCERO { get; set; }

    public string TERCERO_NOMBRE { get; set; }

    public string COMENTARIO { get; set; }

    public string dcofechconta { get; set; }

    public string dcofechtran { get; set; }

    public string dcoprefijo { get; set; }

    public string dcoorigen { get; set; }

    public Nullable<System.DateTime> FECHA { get; set; }

    public Nullable<decimal> INGRESOS_OPERACIONALES { get; set; }

    public Nullable<decimal> COSTO_VENTA { get; set; }

    public Nullable<decimal> OTROS_INGRESOS { get; set; }

    public Nullable<decimal> GASTOS_VENTA { get; set; }

    public Nullable<decimal> OTROS_GASTOS { get; set; }

    public Nullable<decimal> INGRESOS_FINANCIEROS { get; set; }

    public Nullable<decimal> GASTOS_FINANCIEROS { get; set; }

    public Nullable<decimal> IMPUESTOS { get; set; }

    public Nullable<decimal> INTERESES { get; set; }

    public Nullable<decimal> DEPRECIACION { get; set; }

    public Nullable<decimal> AMORTIZACION { get; set; }

    public string CLASE { get; set; }

    public Nullable<decimal> GASTO_ADMINISTRATIVO { get; set; }

}

}
