
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_DETALLE_ADJUNTOS_PERS
{

    public long ID { get; set; }

    public long COD_DETALLE_FACTURA_ADJUNTO_PERS { get; set; }

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<long> COD_ROL { get; set; }

    public Nullable<long> COD_COLABORADOR { get; set; }

    public Nullable<long> COD_FORMAS_PAGO_FECHAS { get; set; }

    public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }

    public string USUARIO { get; set; }

    public Nullable<long> COD_ESTADO_FACTURA { get; set; }

    public Nullable<long> COD_CAUSA_ESTADO { get; set; }

    public string OBSERVACIONES { get; set; }

    public Nullable<long> COD_FACTURA { get; set; }

    public Nullable<long> COD_ESTADO_DETALLE { get; set; }

    public Nullable<long> COD_CONCEPTO_PSL { get; set; }

    public Nullable<long> COD_GRUPO_FACTURA { get; set; }

    public Nullable<decimal> HORAS_ED { get; set; }

    public Nullable<decimal> HORAS_EN { get; set; }

    public Nullable<decimal> HORAS_FD { get; set; }

    public Nullable<decimal> HORAS_FN { get; set; }

    public Nullable<decimal> ADICIONES { get; set; }

    public Nullable<decimal> HORAS_AUSENCIA { get; set; }

    public Nullable<decimal> DESCUENTO_AUSENCIA { get; set; }

    public Nullable<System.DateTime> FECHA_INI { get; set; }

    public Nullable<System.DateTime> FECHA_FIN { get; set; }

    public Nullable<decimal> VALOR_DIAS_LAB { get; set; }

    public Nullable<decimal> VALOR_SIN_IMPUESTOS { get; set; }

    public string NOMBRES { get; set; }

    public string APELLIDOS { get; set; }

    public Nullable<long> CEDULA { get; set; }

    public Nullable<System.DateTime> FECHA_FORMA_PAGO { get; set; }

    public string NOMBRE_PROYECTO { get; set; }

    public string CENTRO_COSTOS { get; set; }

    public string NOMBRE_ROL { get; set; }

    public Nullable<System.DateTime> FECHA_INICIO_EJECUCION { get; set; }

    public Nullable<System.DateTime> FECHA_FIN_EJECUCION { get; set; }

    public string NOMBRE_PERSONA { get; set; }

}

}
