//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_INGEELIMP
    {
        public long COD_CONTRATO_PROYECTO { get; set; }
        public string igecodigo { get; set; }
        public int igeidentificador { get; set; }
        public string igecompania { get; set; }
        public string igedivision { get; set; }
        public string igenombcort { get; set; }
        public string igenomblarg { get; set; }
        public string igeimpuesto { get; set; }
        public string eobcodigo { get; set; }
        public string eobnombre { get; set; }
        public System.DateTime eobfecha { get; set; }
        public string eobusuario { get; set; }
        public int igedivisconta { get; set; }
        public string igecodalter { get; set; }
        public string igedesactivadepre { get; set; }
    }
}
