//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_CONTRATO_PROYECTO_FACTURAS
    {
        public string CENTRO_COSTOS { get; set; }
        public Nullable<long> COD_ESTADO_ORDEN_SERVICIO { get; set; }
        public string COMPLETA { get; set; }
        public string DESCRIPCION { get; set; }
        public long COD_CONTRATO_PROYECTO { get; set; }
        public System.DateTime FECHA_ULTIMA_FACTURA { get; set; }
        public Nullable<int> DIAS_SIN_FACTURAR { get; set; }
        public Nullable<int> MESES_SIN_FACTURAR { get; set; }
        public System.DateTime FECHA_INICIO_EJECUCION_ULTIMO_CONTRATO { get; set; }
        public string ESTADO_ULTIMA_FACTURA { get; set; }
        public string ESTADO_ORDEN { get; set; }
    }
}
