
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_PENDIENTES_RETIRO
{

    public Nullable<long> COD_CONTRATO_PROYECTO { get; set; }

    public Nullable<System.DateTime> FECHA_FIN { get; set; }

    public Nullable<System.DateTime> FECHA_INI { get; set; }

    public long COD_COLABORADOR { get; set; }

    public Nullable<long> COD_CARGO { get; set; }

    public string NOMBRES { get; set; }

    public string APELLIDOS { get; set; }

    public Nullable<long> COD_TIPO_DE_CONTRATO { get; set; }

    public string CENTROS_COSTOS { get; set; }

    public Nullable<long> CEDULA { get; set; }

    public string CENTRO_COSTOS_PROYECTO { get; set; }

    public string DESCRIPCION { get; set; }

    public Nullable<System.DateTime> FECHA_FIN_PACTADA { get; set; }

    public string DESCRIPCION_ROL { get; set; }

    public Nullable<System.DateTime> HOY { get; set; }

}

}
