
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace syncfusion_payc.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VISTA_RESUMEN_GESTION_CARTERA
{

    public string CENTRO_COSTOS { get; set; }

    public string DESCRIPCION_CENTRO_COSTOS { get; set; }

    public Nullable<int> MESES_SIN_FACTURAR { get; set; }

    public Nullable<decimal> TOTAL_FACTURADO { get; set; }

    public Nullable<decimal> TOTAL_SALDO { get; set; }

    public Nullable<System.DateTime> FECHA_INICIO_EJECUCION { get; set; }

    public Nullable<System.DateTime> FECHA_FIN_EJECUCION { get; set; }

    public Nullable<double> TOTAL_CONTRATOS { get; set; }

    public string NUMERO_FACTURA { get; set; }

    public string DOCUMENTO { get; set; }

    public string eobcodigo { get; set; }

    public Nullable<System.DateTime> FECHA_REGISTRO_PAGO { get; set; }

    public Nullable<System.DateTime> FECHA_PAGO { get; set; }

    public string TIPO_PAGO { get; set; }

    public string CONSECTUTIVO_PAGO { get; set; }

    public string COMENTARIO_CORTO { get; set; }

}

}
