//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syncfusion_payc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_GENERACION_PAGADO_COLABORADOR
    {
        public string CEDULA { get; set; }
        public string DESCRIPCION { get; set; }
        public string FECHA_PAGO { get; set; }
        public Nullable<decimal> EGRESOS { get; set; }
        public string dcocomentario { get; set; }
        public string dcocuenta { get; set; }
        public string CECO { get; set; }
    }
}
