//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contratos()
        {
            this.documentos_procesos = new HashSet<documentos_procesos>();
            this.proceso_termino = new HashSet<proceso_termino>();
        }
    
        public long cod_contrato { get; set; }
        public string entidad { get; set; }
        public string tipo_proceso { get; set; }
        public string link_invitacion { get; set; }
        public string estado_proceso { get; set; }
        public string regimen_contratacion { get; set; }
        public string clasificacion_unsp { get; set; }
        public string id_unsp { get; set; }
        public Nullable<long> cuantia { get; set; }
        public string moneda { get; set; }
        public string familia { get; set; }
        public string objeto { get; set; }
        public string tipo_contrato { get; set; }
        public string dept_muni { get; set; }
        public Nullable<System.DateTime> fecha_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string link_secop { get; set; }
        public string depto { get; set; }
        public string cod_secop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_procesos> documentos_procesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proceso_termino> proceso_termino { get; set; }
    }
}
