//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_procesos
    {
        public long cod_documento { get; set; }
        public string descripcion { get; set; }
        public string url { get; set; }
        public string format { get; set; }
        public Nullable<System.DateTime> datepublished { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public Nullable<long> proceso { get; set; }
    
        public virtual contratos contratos { get; set; }
    }
}
