//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class proceso_termino
    {
        public long cod_proceso_termino { get; set; }
        public Nullable<long> proceso { get; set; }
        public string termino { get; set; }
        public string tipo_termino { get; set; }
    
        public virtual contratos contratos { get; set; }
    }
}
