//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class aceptacion_cliente
    {
        public Nullable<System.DateTime> NVACE_FECH { get; set; }
        public string NVENV_ESTN { get; set; }
        public Nullable<System.DateTime> NVENV_FECH { get; set; }
        public Nullable<System.DateTime> NVING_FECH { get; set; }
        public string NVREC_CODI { get; set; }
        public string NVREC_DESC { get; set; }
        public Nullable<System.DateTime> NVREC_FECH { get; set; }
        public string NVREC_OBSE { get; set; }
        public long cod_aceptacion_cliente { get; set; }
    }
}
