//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class aceptacion_dian
    {
        public string description { get; set; }
        public Nullable<System.DateTime> NVENV_FECH { get; set; }
        public string NVENV_RESP { get; set; }
        public string E { get; set; }
        public string ID { get; set; }
        public string T { get; set; }
        public long cod_dian { get; set; }
        public string NVENV_ESTA { get; set; }
        public Nullable<System.DateTime> NVENV_CFEC { get; set; }
        public Nullable<int> ID_MAESTRO { get; set; }
    }
}
