//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_facturas
    {
        public string E { get; set; }
        public string ID { get; set; }
        public string D { get; set; }
        public string result { get; set; }
        public string descripcion { get; set; }
        public string document { get; set; }
        public long cod_documento_factura { get; set; }
    }
}
