//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class envios_noova
    {
        public Nullable<int> ID_MAESTRO { get; set; }
        public int COD_REGISTRO_ENVIOS { get; set; }
        public string ID_FACTURA { get; set; }
        public string ID_DOCUMENTO { get; set; }
        public string ESTADO_CLIENTE { get; set; }
        public string ESTADO_DIAN { get; set; }
    }
}
