//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class FALTANTES_CONFIRMACION
    {
        public int ID_MAESTRO { get; set; }
        public string ID_FACTURA { get; set; }
        public string ID_DOCUMENTO { get; set; }
    }
}
