//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class pruebas
    {
        public Nullable<long> asignacion { get; set; }
        public Nullable<long> usuario { get; set; }
        public string periodicidad { get; set; }
        public string dias_envio { get; set; }
        public Nullable<System.DateTime> hora_envio { get; set; }
        public Nullable<long> ultimo_informe { get; set; }
        public Nullable<System.DateTime> fecha_proximo_envio { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_envio { get; set; }
        public Nullable<long> dia_envio_num { get; set; }
        public Nullable<long> periodicidad_num { get; set; }
        public string estado { get; set; }
        public Nullable<long> dias_para_envio { get; set; }
        public string nombre { get; set; }
        public string color { get; set; }
        public string nombre_usuario { get; set; }
        public long cod_prueba { get; set; }
    }
}
