//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importacion_noova
{
    using System;
    using System.Collections.Generic;
    
    public partial class resoluciones_numeracion_facturas
    {
        public string NumeroResolucion { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public string Prefijo { get; set; }
        public string RangoInicial { get; set; }
        public string RangoFinal { get; set; }
        public Nullable<System.DateTime> FechaVigenciaDesde { get; set; }
        public Nullable<System.DateTime> FechaVigenciaHasta { get; set; }
        public long cod_resolucion_numeracion_facturas { get; set; }
    }
}
